config/routes.rb
Blog::Application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  
  validates :title, :content, :presence => true
  validates :title, :length => { :minimum =>2 }
  validates :title, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts=Post.all
	end
	def show
		@post=Post.find(params[:id])
	end
	def new
		@post=Post.new(params[:post])		
	end
	
	def edit
		@post=Post.find(params[:id])
	end
	def create
		@post=Post.new(params[:post])
		
		if @post.save
			redirect_to posts_path, :notice => "Your post was saved"
		else
			render "new"
		end
	end
	def update
		@post=Post.find(params[:id])
		
		if @post.update_attributes(params[:post])
			redirect_to posts_path, :notice =>" Post updated"
		else
			render "edit"
		end
	end
	def destroy
		@post= Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice =>"your post has been deleted"
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do  |key,value| %>
	<p><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= form_for @post do |f| %>
	<p> 
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p> 
		<%= f.label :content %><br/>
		<%= f.text_area :content %>
	</p>
	<p> 
		<%= f.submit "Update post" %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1>THE BLOG</h1>

<% @posts.each do |post| %>
	<h2><%= link_to post.title, post %></h2>
	<p><%= post.content%></p>
	<p>
		<%= link_to "Edit", edit_post_path(post)%> | 
		<%= link_to "Delete", post, :confirm =>"Are you sure?", :method => :delete %>
	</p>
	
	<hr />
<% end %>

<p><%= link_to "Add New Post", new_post_path%></p>

<!-- Le styles -->
    <link href="/assets/application.css" media="all" rel="stylesheet" type="text/css" />

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
	<%if @post.errors.any? %>
		<h2>Errors:</h2>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<p> 
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p> 
		<%= f.label :content %><br/>
		<%= f.text_area :content %>
	</p>
	<p> 
		<%= f.submit "New post" %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.content %></p>

<p><%= @post.created_at %></p>